# Woodpecker CI configuration
# Builds jellyfin from source on bare metal (requires allow.mlock for .NET)

steps:
  - name: build-latest
    image: /bin/sh
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      GITHUB_ACTOR:
        from_secret: GITHUB_USER
    commands:
      - |
        # Build Jellyfin from source (requires bare metal for .NET mlock)
        chmod +x scripts/build-jellyfin.sh
        doas ./scripts/build-jellyfin.sh

        # Build container image with pre-built artifacts
        mkdir -p scripts
        fetch -qo scripts/build.sh \
          "https://raw.githubusercontent.com/daemonless/daemonless/build-v1.0.0/scripts/build.sh"
        chmod +x scripts/build.sh
        ./scripts/build.sh \
          --doas \
          --registry ghcr.io \
          --image ghcr.io/daemonless/jellyfin \
          --tag latest \
          --tag-version \
          --skip-wip \
          --login --push

when:
  - event: push
    branch: main
    path:
      exclude: [ "*.md", "docs/**", "LICENSE", ".gitignore" ]
  - event: manual
