# Woodpecker CI configuration
# NOTE: :latest currently aliases to :pkg-latest until source build is fixed

steps:
  - name: build-pkg
    image: /bin/sh
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      GITHUB_ACTOR:
        from_secret: GITHUB_USER
    commands:
      - |
        mkdir -p scripts
        fetch -qo scripts/build.sh \
          "https://raw.githubusercontent.com/daemonless/daemonless/build-v1.2.0/scripts/build.sh"
        chmod +x scripts/build.sh

        # Build pkg (quarterly packages)
        ./scripts/build.sh \
          --doas \
          --registry ghcr.io \
          --image ghcr.io/daemonless/jellyfin \
          --containerfile Containerfile.pkg \
          --base-version 15-quarterly \
          --tag pkg \
          --skip-wip \
          --login --push

  - name: build-pkg-latest
    image: /bin/sh
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      GITHUB_ACTOR:
        from_secret: GITHUB_USER
    commands:
      - |
        mkdir -p scripts
        fetch -qo scripts/build.sh \
          "https://raw.githubusercontent.com/daemonless/daemonless/build-v1.2.0/scripts/build.sh"
        chmod +x scripts/build.sh

        # Build pkg-latest and also tag as latest
        ./scripts/build.sh \
          --doas \
          --registry ghcr.io \
          --image ghcr.io/daemonless/jellyfin \
          --containerfile Containerfile.pkg \
          --base-version 15 \
          --tag pkg-latest \
          --alias latest \
          --skip-wip \
          --login --push

when:
  - event: push
    branch: main
    path:
      exclude: ["*.md", "docs/**", "LICENSE", ".gitignore"]
  - event: manual
