#!/bin/sh

# Use jellyfin-ffmpeg by default if not specified
FFMPEG_PATH="${FFMPEG_PATH:-/usr/local/bin/jellyfin-ffmpeg}"

exec s6-setuidgid bsd /usr/local/jellyfin/jellyfin \
    --datadir /config \
    --cachedir /cache \
    --ffmpeg "${FFMPEG_PATH}" \
    --webdir /usr/local/jellyfin/jellyfin-web